### ISSUE TITLE
macOS Sierra

### ISSUE THREAD

**Issue by johnbender** [filamentgroup/gulpicon#8]
Related to:

https://github.com/filamentgroup/grunticon-lib/issues/26

**Comment by johnbender** [comment]
@designchief 

Can you try the following in your project `package.json`: 

```
...
"gulpicon": "filamentgroup/gulpicon#update-grunticon-lib "
...
```

**Comment by designchief** [comment]
@johnbender

That update to gulpicon worked for me, cheers

**Comment by johnbender** [comment]
@designchief 

Ok we've published a new version to npm (1.0 because it should have been long ago):

```
...
"gulpicon": "^1.0.0"
...
```

**Comment by designchief** [comment]
Perfect, just updated to that and all worked as expected too, thanks for your help @johnbender

**Comment by johnbender** [comment]
@designchief 

No problem, thanks for notifying us about the issue!
