### ISSUE TITLE
The 'enhanceSVG: true' flag doesn't seem to generate correct grunticon.loader.js

### ISSUE THREAD

**Issue by jgrassis** [filamentgroup/gulpicon#9]
I can run the _Grunticon_ module with the **enhanceSVG** flag set to true, and the SVG is properly injected into the page. But when I run _Gulpicon_ wtih the **enhanceSVG** flag set to true, it does NOT inject the SVG into the page. 

However, if I copy the grunticon.loader.js from my project using _Grunticon_ into my project using _Gulpicon_, it works perfectly. I ran a diff on the two files, and there is definitely a (very minor) difference between what is generated.  Once the file is prettified, ~ lines 55 and 56 are different:

**Grunticon**:
`var o = c(i(e.href)); "function" == typeof t ? (s(n, o), t()) : s(o), "function" == typeof n && n() }) };
e.embedIcons = s, e.getCSS = i, e.getIcons = c, e.ready = a, e.svgLoadedCallback = d, e.embedSVG = d }(grunticon, this) }();`

**Gulpicon**:
`var o = c(i(e.href)); "function" == typeof t ? (s(n, o), t()) : "function" == typeof n && (s(o), n()) }) };
e.embedIcons = s, e.getCSS = i, e.getIcons = c, e.ready = a, e.svgLoadedCallback = d, e.embedSVG = d }(grunticon, this) }();`

Any thoughts?

**Comment by richhiggins** [comment]
^ Having the exact same issue, I dropped in a loader snippet from an earlier release (0.1.2) and it started working.

**Comment by johnbender** [comment]
@jgrassis @richhiggins 

The `grunticon-lib` version has been updated and the package version has been changed to match (ie, we released version 1.2.1). 

Please update your dependencies and let me know if you have any issues.
